import { Vazirmatn } from "next/font/google";
import "./globals.css";
import MainLayout from "@/components/layout/MainLayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const vazir = Vazirmatn({ subsets: ["arabic"] });


export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body
        className={`${vazir.className} antialiased`} dir="rtl"
      >
        <MainLayout>
        {children}
        </MainLayout>
      </body>
    </html>
  );
}
